### ISSUE TITLE
Add a demo design to Issie

### ISSUE THREAD

**Issue by tomcl** [tomcl/issie#314] opened 2023-07-16 10:52 UTC
It would be useful to have a demo design (or even several) built into Issie so that they could be loaded via project menu commands "load CPU demo", "load counter demo", etc.

The work to do this is:

- Note how static file "assets" can be included in Issie and from the file system: see renderer/testAssets and try this function out from the `print static assets` sheet menu running Issie under `npm run dev`.
- Add a directory containing a demo Issie project to static assets
- Using the functions in FilesIO.fs write a file menu command with a submenu that reads a demo project from static assets, writes it to the normal user file system, then loads it as normal. Writing to user file system should use "create project" dialog to work out where to put the demo project - maybe with a fixed project name.
- Add a set of demo projects using a submenu to select which one is loaded.

Get ideas from multiple people including me as to what demo hardware in Issie might be useful for.

**Comment by IlanIwumbwe** [comment] 2023-08-31 13:07
May I please be assigned to this issue?

**Comment by IlanIwumbwe** [comment] 2023-09-06 17:26
when loading projects, should I make it such that the loaded demo becomes the current project, or should I just make it the last used directory, such that the user can import the sheet into their current project?

**Comment by IlanIwumbwe** [comment] 2023-09-06 17:51
**Update**

I've got it such that the menu looks like so:
![image](https://github.com/tomcl/issie/assets/56346800/ee7c8c71-4190-468e-99bb-c1644fe91804)
 - In the future when new demos get created, they each get their own menu option.
 - When selected, a file selector comes up, asking the user for the directory into which demo should be copied
 - Copying into directories isn't allowed. Directory names already existing isn't an issue, since in file selector, if user types such a name they are redirected to that directory
 - The project is copied over successfully.

The next stage is to make demos and add them to the menu

**Comment by tomcl** [comment] 2023-09-06 19:09
Demos should be loaded, I think, into a special directory inside the Issie executable directory.

**Comment by tomcl** [comment] 2023-09-06 19:28
One thing – there should probably be the facility easily to add multiple demos?

**Comment by tomcl** [comment] 2023-09-06 19:38
How about adding a “open demo project” link to the initial project open menu? And make this go to a chooser screen with (neat – same width) buttons for each demo.

**Comment by IlanIwumbwe** [comment] 2023-09-07 04:03
I like the idea of adding an "open demo project" link on the initial project open menu. I will work on this, and add functionality for multiple demos on the chooser screen, which shouldn't be too hard.

**Comment by tomcl** [comment] 2023-09-07 07:53
Yes! The chooser screen can say a bit about each demo, as well…

**Comment by tomcl** [comment] 2023-09-07 07:58
Probably the correct sematics (which needs to be made clear on the popup screen) is:


  *   When you close and reopen a demo project you get the original hardware copied again.
  *   To write your own hardware you should open  anew project.

**Comment by IlanIwumbwe** [comment] 2023-09-07 10:02
I see. At the moment, the user effectively creates a new project but with components from the demo file in some directory they choose. When they load demo project, the hardware will be the initial demo hardware, but if they open the project they created from before, it will contain any changes made like any other project would.

Is this fine, or should it be that saving a copy of the demo project then building onto it if you so wish shouldn't be allowed?

**Comment by tomcl** [comment] 2023-09-07 10:06
The only issue is that to make it v easy to check stuff with demos it might be good to have auto-placed directory inside Issie binaries? Personally it is always a pain for me to decide where to put projects till I have this set up as standard. What do you think?

**Comment by IlanIwumbwe** [comment] 2023-09-07 10:43
Ah I see. I'll set it up to automatically set up a demos directory in Issie executable directory, such that when the user chooses some demo file, it gets copied over from static to this demos directory.

**Comment by tomcl** [comment] 2023-09-07 10:46
Yes. I am not 100% sure about this. But I think so. With the idea that choosing a demo again simply overwrites any previous copy.

**Comment by IlanIwumbwe** [comment] 2023-09-07 11:18
Yes.

I may be missing something, but I can't get popups to work from the initial unclosable popup menu. I keep getting exception errors, but I'm not sure where they are coming from.

**Comment by tomcl** [comment] 2023-09-07 11:42
Ah – yes maybe they are called from the view function only when project is open.

**Comment by IlanIwumbwe** [comment] 2023-09-07 12:14
I thought that as well, so I moved the button under the Project tab, such that at that point, there's an open project, but that didn't work either. I funnelled it down to this function being the cause of the error:        
let demosList =
            div [] [
                Table.table [] [
                        thead [] [ tr [] (List.map headCell ["Demo" ;"Information"; "Decision"]) ]
                        tbody [] (  FilesIO.readdir demos
                                    |> Array.map (fun path -> 
                                        demoContent path ) )
                       
                ]
            ]
But I'm not sure why it doesn't work

**Comment by tomcl** [comment] 2023-09-07 13:28
I will look at this this evening.

**Comment by IlanIwumbwe** [comment] 2023-09-07 13:45
Alright. Thank you very much

**Comment by IlanIwumbwe** [comment] 2023-09-08 16:07
**Update**

Menu looks like this:
![Screenshot (90)](https://github.com/tomcl/issie/assets/56346800/c1c67d83-8689-4a30-af79-7cf88b7268a6)

Popup looks like this:
![Screenshot (92)](https://github.com/tomcl/issie/assets/56346800/10042acc-fefd-496d-a57e-22db7ffe37e1)

Loading choice:
![Screenshot (93)](https://github.com/tomcl/issie/assets/56346800/4efae7b6-99c2-4748-9a8d-26af217692d7)

Pressing "Open Demo" loads demo as current project.

**Comment by tomcl** [comment] 2023-09-08 19:54
Ok, so these things are a matter of personal opinion in part.


  1.  Re popup – I would have clickable rows same as initial screen (with cancel – but no OK). Each row could be:
  2.  Project name, description, number of components, number of design sheets

For what demos it would be good to have one demo – it could be the eep1 register file which currently has v complex wireing – rearranged using lots of wire labels. Since people do not know much about them.

Re recents; I can see why you like this but I am on side of not making it easy to download and adapt demos. I feel it is complex. I would juts leave them out of recents so that changes are never persistent. I realise this is opinionated.

**Comment by IlanIwumbwe** [comment] 2023-09-08 20:15
Alright.
Thank you for the feedback

**Comment by IlanIwumbwe** [comment] 2023-09-09 12:15
**Update**

The demo project select menu now looks like this:
![image](https://github.com/tomcl/issie/assets/56346800/fe89b851-e88a-45ec-88fe-0fb26baf7088)

Clicking the row makes that demo the current project, without adding the directory to the recents listing. 

The register file is the same one from eep1, I just added a lot of wire labels:
![image](https://github.com/tomcl/issie/assets/56346800/21450f73-403d-4902-ba2f-caaa459e1766)

**Comment by tomcl** [comment] 2023-09-09 12:32
Demo project popup – great. I hope you agree with me that simple & clean UIs are good!

Wire labels: surely the real merit of wrie labels comes when you label each of the outputs – and each of the inputs – avoiding all of that wiring?

**Comment by tomcl** [comment] 2023-09-09 12:33
Oh – suggest “register regx16x8 file from eep1 demo using wire labels to simplify wiring”

**Comment by tomcl** [comment] 2023-09-09 12:34
(sorry)

Suggest – fulladder (simpest) fist – then eep1 – then simplified register file?

**Comment by IlanIwumbwe** [comment] 2023-09-09 12:37
Yes, clean UIs are great!

Oh, I completely forgot how to use wire labels to simplify wiring. That's a silly error, I will correct this.

I agree with the demo listing, this will be implemented.

**Comment by IlanIwumbwe** [comment] 2023-09-09 13:03
![image](https://github.com/tomcl/issie/assets/56346800/385df909-c237-4dc8-b013-16aafd4923df)
New register file design

**Comment by tomcl** [comment] 2023-09-09 13:06
Yes! I think on balance I’d do Din as wires without labels – no crossing is needed with all the other labels.

**Comment by IlanIwumbwe** [comment] 2023-09-09 13:09
Oh yes, that makes sense

**Comment by tomcl** [comment] 2023-09-09 13:10
Or – maybe I would keep DIN as wire labels and use wires (no intersections)for the enables?

**Comment by IlanIwumbwe** [comment] 2023-09-09 13:24
I like having DIN as wires, since I think it is intuitive to see that the same data goes to the inputs, while the enable bits are decided upon by the input address.

**Closed** 2023-09-10 16:00 UTC
Labels: good first issue, Summer 2023
